# Generated by Django 3.2.9 on 2023-12-26 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('user_icon', models.ImageField(blank=True, null=True, upload_to='user_icons/')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
            ],
        ),
    ]
