# Generated by Django 3.2.9 on 2023-12-27 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20231227_0603'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile2',
            new_name='UserProfile',
        ),
    ]
