# Generated by Django 3.2.9 on 2023-12-28 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
